# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    app.circular_reference_handler:
        class: App\Service\CircularReferenceHandler

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\EventListener\JsonRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }
    App\EventListener\SecuritySubscriber:
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    App\Service\Serializer:
        arguments:
            $serializer: '@serializer'
    Mailtrap\MailtrapClient:
        arguments:
            - '%env(MAILER_API_TOKEN)%'
    Mailtrap\Bridge\Transport\MailtrapTransportFactory:
        tags:
            - { name: 'mailer.transport_factory' }
